# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Do the job on the runner
    runs-on: ubuntu-latest
    
    steps:
      - name: Check utilities
        run: git --version

      - name: Frontend
        run: |
          cd ..
          cd Hostel-Management-FE
          npm
          npm install
          npm ng build
